main: community.leaf.examples.tasks.bukkit.TasksExampleBukkitPlugin
name: ${project.name}
version: ${revision}
api-version: 1.13

commands:
  taskstest:
    aliases: [tasks-test, test-tasks, testtasks]
    permission: tasks.example
